app:
  eureka-hostname: localhost
  eureka-port: 8761
  server-port: 8084
  application-name: notification-service
  kafka-hostname: localhost
  kafka-port: 9092
  kafka-default-topic: notificationTopic
  kafka-concurrency: 3
  kafka-group-id: notificationId
  context-path: api/notification
  api-gateway-hostname: localhost
  swagger-api-gateway-hostname: localhost
  api-gateway-server-port: 8181
  zipkin-hostname: localhost
  zipkin-server-port: 9411
  zipkin-context-path: api/v2/spans
  swagger-info-title: Notification Service
  swagger-info-version: v1.0
  keycloak-host: localhost
  keycloak-port: 8090
  redis-host: localhost
  redis-port: 6379
  redis-time-to-live: 600000 #10 minutes #ms

security:
  enabled: true
  skip-urls:
    - /guest/**
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api-docs/**
    - /error/**

spring:
  application:
    name: ${app.application-name}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.keycloak-host}:${app.keycloak-port}/realms/spring-boot-microservices-realm
  kafka:
    enabled: true
    bootstrap-servers: ${app.kafka-hostname}:${app.kafka-port}
    template:
      default-topic: ${app.kafka-default-topic}
    consumers:
      internal-consumer:
        topic-name: internalTopic
        group-id: internalId-${app.application-name}
        properties:
          concurrency: ${app.kafka-concurrency}
      notification-consumer:
        topic-name: notificationTopic
        group-id: notificationId-${app.application-name}
        properties:
          concurrency: ${app.kafka-concurrency}
  redis:
    enabled: true
  cache:
    redis:
      time-to-live: ${app.redis-time-to-live}
    type: redis
  data:
    redis:
      host: ${app.redis-host}
      port: ${app.redis-port}
#    consumer:
#      properties:
#        concurrency: ${app.kafka-concurrency}
#      group-id: ${app.kafka-group-id}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-hostname}:${app.eureka-port}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

management:
  tracing:
    enabled: true
    propagation:
      type: b3
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://${app.zipkin-hostname}:${app.zipkin-server-port}/${app.zipkin-context-path}

server:
  port: ${app.server-port}
  servlet:
    context-path: /${app.context-path}

logging:
  level:
    root: INFO
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

swagger:
  server:
    url: http://${app.swagger-api-gateway-hostname}:${app.api-gateway-server-port}/${app.context-path}
  info:
    title: ${app.swagger-info-title}
    version: ${app.swagger-info-version}
    description: Documentation ${app.swagger-info-title} ${app.swagger-info-version}
  security-scheme:
    name: bearerAuth
    bearer-format: JWT
    scheme: bearer